confess/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^web/',include('web.urls')),
    url(r'^api/posts/',include('web.api.urls')),

]

web/api/urls.py
from django.conf.urls import url
from web.api.views import PostsApiView
from rest_framework import routers



router = routers.DefaultRouter()

urlpatterns =[
url(r'^$',PostsApiView.as_view(),name='home page api'),

]

web/urls.py
from django.conf.urls import url
from web import views
from rest_framework import routers



router = routers.DefaultRouter()

urlpatterns =[
url(r'^$',views.home,name='home page'),
url(r'^home/$',views.home,name='home page'),
url(r'^post/(?P<pk>\d+)/$',views.singlepost,name='singlepost'),
url(r'^post/new/$',views.newpost,name='newpost'),
url(r'^post/edit/$',views.editpost,name='editpost'),
url(r'^post/submit/$',views.submitapi,name='submit'),
]

web/models.py
from __future__ import unicode_literals
import datetime
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Post(models.Model):

    confessionmodes=(
    ('d','dream'),('f','fantasy'),('fi','first experience'),('g','guilt'),('l','lie'),('p','pain'),('q','question'),('r','random feeling'),
    ('t','truth'),('w','wild experience'),('o','others')
    )
    text = models.CharField(max_length=300)
    summery = models.CharField(max_length=50,default="")
    confessmode= models.CharField(max_length=2,choices=confessionmodes)
    publishdate=models.DateTimeField(blank=True)


    def publish(self):
        self.publishdate=datetime.datetime.now()
        self.save()
    def __str__(self):
        return "{}".format(self.text)

web/forms.py
from django import forms
from web.models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields= ('text','confessmode')

web/api/views.py
from rest_framework.generics import ListAPIView
from web.api.serializers import postserializer
from web.models import Post


class PostsApiView(ListAPIView):
    queryset = Post.objects.all().order_by('-publishdate')
    serializer_class = postserializer

web/views.py
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.models import User, Group
from web.serializers import UserSerializer, GroupSerializer
from rest_framework import viewsets
from django.http import HttpResponse,JsonResponse
import json
from web.models import Post
from web.forms import PostForm
import datetime
from django.shortcuts import redirect
from django.views.decorators.csrf import csrf_exempt
from django.utils.encoding import smart_str
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

# Create your views here.
@csrf_exempt




def home(request):
    posts = Post.objects.all()
    timenow =datetime.datetime.now()
    return render(request,'posts.html',{'time':timenow,'posts':posts})


def singlepost(request,pk):
    posts = get_object_or_404(Post,pk=pk)
    return render(request,'singlepost.html',{'singlepost':posts})

def newpost(request):
    if (request.method=="POST"):
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.publish()
        return redirect('singlepost',pk=post.pk)

    else :
        form = PostForm()
        return render(request,'newpost.html',{'form':form})


@csrf_exempt


def submitapi(request):
    posteddata= request.POST
    text= smart_str(posteddata['text'])
    summery = text[0:50]+" ..."
    mode= posteddata['mode']
    if(len(text)<400):
            newsubmit= Post(text=text,confessmode=mode,summery=summery)
            newsubmit.publish()
            return HttpResponse("ok!")
    else:
        return HttpResponse("nope!")






def editpost(request):
    form = PostForm()
    return render('newpost.html',{'form':form})

web/templates/base.html
{% load staticfiles %}
<html>
<head>
<title>confession</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.3.0/react.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.3.0/react-dom.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.14.0-alpha1/JSXTransformer.js"></script>
<link rel="stylesheet" href="{% static 'css/web.css'%}">





</head>

  <body >

<div id="titleofpage" >
<h1>here you can confess to all you have done in past </h1>
</br>
<h2>or just what you have im mind to do ! </h2>
</div>

<a href ="{% url 'newpost' %}"class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
<button  onclick="renderedapp.shownextpage()" class="top-menu">next</button>


<div class="container" id="table" >

  <table class="table table-bordered table-hover" >
    <thead>
      <tr>
        <th>موضوعات</th>

      </tr>
    </thead>
    <tbody>
      <tr>
        <td>یک آرزو</td>

      </tr>
      <tr>
        <td>یک فانتزی</td>

      </tr>
      <tr>
        <td>اولین تجربه</td>

      </tr>
    </tbody>
  </table>
</div>




<div id = "posts">
  <div class="container">
    <div class="row">
      <div class="col-md-16">


</div>
</div>
</div>



</div>




</body>



<script type="text/jsx">
var postsjson;
var gotthejson =false;
class App extends React.Component{
  constructor(){
    super();
    this.state={
      pagenumber:1,
      postsjson:"",
    }

    fetch('http://localhost:8080/api/posts/?format=json', {
      method: 'get'
    }).then(function(response) {
    return  response.json().then(function(json){
      postsjson=json;


})

});


  }

shownextpage(){
gotthejson =true;
  this.setState({pagenumber:this.state.pagenumber+1});
}

render(){
  if(gotthejson>0){
var components =[];
for(var i=1; i<10;i++){
  console.log(postsjson);
  var text =postsjson[i]["text"];
  components.push(
      <Greeting text={text} />
  )
}
}
  return(
    <div>
actual fucking happens here! pagenumber {components}
    </div>
  )

}



}




class Greeting extends React.Component {
    render(){
        return(
            <div> {this.props.text} </div>
        )
    }
}



var renderedapp =ReactDOM.render(<App/>,document.getElementById('posts'));


</script>



</html>

web/templates/newpost.html
here we submit forms!
{% block content%}


<form action="" method="post" class="post-form"> {% csrf_token%}
<h1>{{form}}</h1>
<button  class="save btn btn-default"> save </button>
<form>
{% endblock %}

web/templates/posts.html
{% extends 'base.html'%}





{% block content%}
<ul>
{% for post in posts %}
<li>
  <a href="{% url 'editpost'  %}" class="top-menu"><span class="glyphicon glyphicon-edit" ></span></a>
  <h2>{{post.get_confessmode_display}}</h2>
<a href="{% url 'singlepost' pk=post.pk %}">{{post.summery}}</a>
</li>
{% endfor %}
</ul>
{% endblock%}

web/templates/singlepost.html
{% extends 'base.html' %}


{% block content%}

<p>{{ singlepost.text }}</p>

{% endblock %}